version: "3.9"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kvinpword124

  web:
    build: .
    volumes:
      - .:/home/nserv
    ports:
      - "8080:8080"
  